## Importing Required Libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
df = pd.read_csv('Social_Network_Ads.csv')
df

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [ ]:
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
df.head(10)

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0
5   27            58000          0
6   27            84000          0
7   32           150000          1
8   25            33000          0
9   35            65000          0

## EDA

In [ ]:
df.describe()

Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

In [ ]:
df['Purchased'].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [ ]:
df.corr()

Age  EstimatedSalary  Purchased
Age              1.000000         0.155238   0.622454
EstimatedSalary  0.155238         1.000000   0.362083
Purchased        0.622454         0.362083   1.000000

## Spliting the dataset

In [ ]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [ ]:
df.isna()

Age  EstimatedSalary  Purchased
0    False            False      False
1    False            False      False
2    False            False      False
3    False            False      False
4    False            False      False
..     ...              ...        ...
395  False            False      False
396  False            False      False
397  False            False      False
398  False            False      False
399  False            False      False

[400 rows x 3 columns]

### Splitting in train and test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=50)

In [ ]:
print(X_train)

[[    41  71000]
 [    48  90000]
 [    38  55000]
 [    36 144000]
 [    49  65000]
 [    43 112000]
 [    51 146000]
 [    42 104000]
 [    35  71000]
 [    46  79000]
 [    32 117000]
 [    28  89000]
 [    40  57000]
 [    46  22000]
 [    40  71000]
 [    60  34000]
 [    41  72000]
 [    40  78000]
 [    29 148000]
 [    32  18000]
 [    42  80000]
 [    47  20000]
 [    28  37000]
 [    22  81000]
 [    59  76000]
 [    37  75000]
 [    58 144000]
 [    51  23000]
 [    34  43000]
 [    38 113000]
 [    30 135000]
 [    33  60000]
 [    31 118000]
 [    40  61000]
 [    29  80000]
 [    26  86000]
 [    43 133000]
 [    37  77000]
 [    52 114000]
 [    38  61000]
 [    41  87000]
 [    30 107000]
 [    50  88000]
 [    24  19000]
 [    46  32000]
 [    25  22000]
 [    27  31000]
 [    39  75000]
 [    32 100000]
 [    48  29000]
 [    46  82000]
 [    30  62000]
 [    57  33000]
 [    40 142000]
 [    33  51000]
 [    35  58000]
 [    53  34000]
 [    20  23000]
 [    20  4900

In [ ]:
y_test

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1])

## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[ 0.24534512  0.02320768]
 [ 0.90758772  0.57439019]
 [-0.03847314 -0.44094601]
 [-0.22768531  2.14090889]
 [ 1.0021938  -0.15084995]
 [ 0.43455729  1.21260151]
 [ 1.19140597  2.19892811]
 [ 0.3399512   0.98052467]
 [-0.3222914   0.02320768]
 [ 0.71837554  0.25528453]
 [-0.60610966  1.35764954]
 [-0.984534    0.54538059]
 [ 0.15073903 -0.38292679]
 [ 0.71837554 -1.39826299]
 [ 0.15073903  0.02320768]
 [ 2.04286074 -1.05014772]
 [ 0.24534512  0.05221729]
 [ 0.15073903  0.22627492]
 [-0.88992791  2.25694732]
 [-0.60610966 -1.51430141]
 [ 0.3399512   0.28429413]
 [ 0.81298163 -1.4562822 ]
 [-0.984534   -0.96311891]
 [-1.55217051  0.31330374]
 [ 1.94825466  0.16825571]
 [-0.13307923  0.13924611]
 [ 1.85364857  2.14090889]
 [ 1.19140597 -1.36925338]
 [-0.41689748 -0.78906127]
 [-0.03847314  1.24161112]
 [-0.79532183  1.87982244]
 [-0.51150357 -0.29589798]
 [-0.70071574  1.38665915]
 [ 0.15073903 -0.26688837]
 [-0.88992791  0.28429413]
 [-1.17374617  0.45835177]
 [ 0.43455729  1.82180323]
 

## Training the naive bayes model

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [ ]:
print(classifier.predict(sc.transform([[30, 140000]])))

[1]


## Predicting Test set result

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]]


## Making The confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[68  2]
 [ 7 23]]
0.91


In [ ]:
print(accuracy_score(y_test, y_pred))
